### ISSUE TITLE
Undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by nemoeslovo** [fastlane/cert#32]
I use to set up username field in cert action and DELIVER_PASSWORD as env variables in Jenkins machine and everything worked perfectly, but with one of the latest update I start getting following error:

```
[12:58:45]: ------------------
[12:58:45]: --- Step: cert ---
[12:58:45]: ------------------
No username or password given. You can set environment variables:
DELIVER_USER, DELIVER_PASSWORD
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
More information about that on GitHub: https://github.com/fastlane/CredentialsManager
-------------------------------------------------------------------------------------
Username: [12:58:45]: undefined method `strip' for nil:NilClass
[12:58:45]: You passed invalid parameters to 'cert'.
[12:58:45]: Check out the error below and available options by running `fastlane action cert`
[12:58:45]: Variable Dump:
[12:58:45]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build_dev", :VERSION_NUMBER=>"1.0.0", :BUILD_NUMBER=>0}
[12:58:45]: Invalid default value for username, doesn't match verify_block
```

**Comment by nemoeslovo** [comment]
even when try to use CLI for cert. I think these issues are related

```
$ cert -u "dev@companyname.com"
No username or password given. You can set environment variables:
DELIVER_USER, DELIVER_PASSWORD
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
More information about that on GitHub: https://github.com/fastlane/CredentialsManager
-------------------------------------------------------------------------------------
Username:
```

**Comment by nemoeslovo** [comment]
finally I fixed it after put the apple_id in Appfile, everything starts working, but I didn't figured out why. As far as I get from the interrupted stack trace 

```
Username: ^C
/Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/highline-1.7.3/lib/highline.rb:870:in `gets': Interrupt
	from /Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/highline-1.7.3/lib/highline.rb:870:in `get_line'
	from /Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/highline-1.7.3/lib/highline.rb:891:in `get_response'
	from /Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/highline-1.7.3/lib/highline.rb:264:in `ask'
	from /Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/credentials_manager-0.7.4/lib/credentials_manager/password_manager.rb:77:in `ask_for_login'
	from /Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/credentials_manager-0.7.4/lib/credentials_manager/password_manager.rb:54:in `initialize'
	from /Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/credentials_manager-0.7.4/lib/credentials_manager/password_manager.rb:23:in `new'
	from /Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/credentials_manager-0.7.4/lib/credentials_manager/password_manager.rb:23:in `shared_manager'
	from /Users/nemoeslovo/.rvm/gems/ruby-2.2.1@[appname]/gems/cert-0.3.0/lib/cert/options.rb:18:in `block in available_options'
```

we are entering to the password manager at the verify options step and  the thing is that password manager has a priority of explicit parameter and DELIVER_USER env variable 

```ruby
self.username ||= id_to_use || ENV["DELIVER_USER"] || AppfileConfig.try_fetch_value(:apple_id) || load_from_keychain[0]
```

which I specified correctly before. So I still believe that it's some kind of bug

**Comment by KrauseFx** [comment]
Thanks for the information and reporting this issue. This is something I *really* want to improve over the next few weeks. This part of `fastlane` will be rewritten.

Did you find a temporary solution that works for you?

**Comment by nemoeslovo** [comment]
yes, it was enough to put correct `apple_id` or remove it from the `Appfile`. thanks a lot!

**Comment by vorobievalex** [comment]
Similar error appeared for me ones form 10 builds. Other builds were successful. My appfiles contain empty or no ids.
Even it seems to be in a different part of app, hope it will help during rework:

/Users/Shared/Jenkins/.gem/gems/highline-1.7.8/lib/highline/question.rb:413:in `remove_whitespace': undefined method `strip' for nil:NilClass (NoMethodError)
	from /Users/Shared/Jenkins/.gem/gems/highline-1.7.8/lib/highline.rb:873:in `get_line'
	from /Users/Shared/Jenkins/.gem/gems/highline-1.7.8/lib/highline.rb:891:in `get_response'
	from /Users/Shared/Jenkins/.gem/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
	from /Users/Shared/Jenkins/.gem/gems/pilot-1.0.0/lib/pilot/manager.rb:54:in `fetch_app_identifier'
	from /Users/Shared/Jenkins/.gem/gems/pilot-1.0.0/lib/pilot/manager.rb:38:in `fetch_app_id'
	from /Users/Shared/Jenkins/.gem/gems/pilot-1.0.0/lib/pilot/manager.rb:21:in `app'
	from /Users/Shared/Jenkins/.gem/gems/pilot-1.0.0/lib/pilot/build_manager.rb:8:in `upload'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/actions/pilot.rb:15:in `run'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from ../../../Common/fastlane/CommonFastfile:37:in `block (2 levels) in parsing_binding'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:109:in `try_switch_to_lane'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:60:in `block (2 levels) in parsing_binding'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:109:in `try_switch_to_lane'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:45:in `block (2 levels) in parsing_binding'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/Shared/Jenkins/.gem/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/.gem/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/.gem/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/Shared/Jenkins/.gem/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/Shared/Jenkins/.gem/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/Shared/Jenkins/.gem/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/bin/fastlane:152:in `run'
	from /Users/Shared/Jenkins/.gem/gems/fastlane-1.37.0/bin/fastlane:158:in `<top (required)>'
	from /Users/Shared/Jenkins/.gem/bin/fastlane:23:in `load'
	from /Users/Shared/Jenkins/.gem/bin/fastlane:23:in `<main>'

**Comment by KrauseFx** [comment]
@vorobievalex it doesn't look like your error is related. Please share your full configuration, including the `Appfile` and the output when running `fastlane`.

**Comment by vorobievalex** [comment]
This did not reproduce for me with newer versions.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1811. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
