### ISSUE TITLE
Default behavior with force flag set to false?

### ISSUE THREAD

**Issue by zats** [fastlane/cert#62]
While running `cert` on a new machine (I forgot to provision it with certificate) I noticed that that `cert` created a new certificate with `force` flag set to `false`.
Is there a way to tell `cert` to fail unless certificate + matching private key exists (locally or remotely) instead of creating a new certificate for my private key?
Thanks!

**Comment by KrauseFx** [comment]
No, currently `cert` is designed to prepare a key + certificate at the end of its run. It is recommended to use [match](https://github.com/fastlane/match) though.

**Comment by zats** [comment]
I actually thought about using chef <https://www.chef.io> instead: we are
using Enterprise certificates for in house distribution. And, as it pointed
out in the match readme, unlike regular certificates it might bring more
problems if compromised. Hence I wanted to use knife
<https://docs.chef.io/knife.html> to extract certificate shared among all
developers.
