### ISSUE TITLE
Couldn't find an existing certificate... creating a new one

### ISSUE THREAD

**Issue by ShelinShelin** [fastlane/cert#76]
show that: 
Certificate XXXXXXXXX (iOS Development) can't be found on your local computer
Couldn't find an existing certificate... creating a new one

In fact, it existed a certificate in develop center,but can not find it

**Comment by ShelinShelin** [comment]
#development
fastlane cert create --development -o $FILE_OUTPUT_PATH
#distribution
fastlane cert  -o $FILE_OUTPUT_PATH

**Comment by KrauseFx** [comment]
Please submit the issue to the fastlane main repo: https://github.com/fastlane/fastlane
